### ISSUE TITLE
Gradle versions conflict

### ISSUE THREAD

**Issue by brun0xon** [InvisibleWrench/FlutterMidiCommand#10]
* What went wrong:
A problem occurred evaluating root project 'flutter_midi_command'.
> Failed to apply plugin [id 'com.android.library']
   > Minimum supported Gradle version is 5.1.1. Current version is 4.10.2. If using the gradle wrapper, try editing the distributionUrl in D:\Programs\Flutter_SDK\.pub-cache\hosted\pub.dartlang.org\flutter_midi_command-0.1.3\android\gradle\wrapper\gradle-wrapper.properties to gradle-5.1.1-all.zip

**Comment by mortenboye** [comment]
Gradle dep updated in 
https://github.com/InvisibleWrench/FlutterMidiCommand/commit/67b6481ec2ce2da439fab442cf84c3d9d71c8f14
Let me know if it doesn't work for you
