### ISSUE TITLE
Question about parsing MIDI start / stop / continue messages

### ISSUE THREAD

**Issue by intonarumori** [InvisibleWrench/FlutterMidiCommand#104]
I was wondering if there was a plan to add MIDI message parsing to the project.

I'm parsing MIDI CC, Midi Start / Stop / Continue messages in my project and was wondering if it would be useful to include it in the project itself, I would be interested in contributing.

Let me know, cheers.

**Comment by mortenboye** [comment]
Hi @intonarumori, thank you for your suggestion. 

I can see a MIDI message parser being useful, so if you are up for it, your contribution is very welcome. 

In terms of the structure i would imagine it being an object you can instantiate, which listens for the raw (current) stream of midi data, parses this into Message objects and outputs those through its own stream.

Perhaps it could also have some filtering, in case one is only interested in a certain type of messages or messages on a specific channel etc. That could also be up to user to filter the stream data before using it.

**Comment by intonarumori** [comment]
Thanks for the reply.
I ended up creating https://github.com/intonarumori/dart_midi_message for now.
This is very simplistic and only does the basic parsing of messages so I'm leaving a reference here and close this issue.
