### ISSUE TITLE
SysExMessage.send()  can not use free format data content.

### ISSUE THREAD

**Issue by yosogawa** [InvisibleWrench/FlutterMidiCommand#105]
I found an issue while checking this plugin.

```
class SysExMessage extends MidiMessage {
  List<int> headerData;
  int value;

  /// System Exclusive Message
  SysExMessage({this.headerData = const [], this.value = 0});

  @override
  void send() {
    data = Uint8List.fromList(headerData);
    data.insert(0, 0xF0); // Start byte
    data.addAll(_bytesForValue(value));
    data.add(0xF7); // End byte
    super.send();
  }



```
It can only be used in limited ways to represent data. (headerdata + data())

The content data enclosed in F0-F7 of SysExMessage.send() is in a free data format. I'm sure every vendor in the world has communications that don't require value.

Please provide a means to send bulk data consisting only of byte (header) data.

**Comment by intonarumori** [comment]
@yosogawa You can do this by using `MidiCommand().send(data)` directly. Send any data array you want with your desired format.
You might be right that `SysExMessage` was implemented with a narrower use-case in mind, and it would be worth rethinking it a bit, but until then you can use `MidiCommand().send(data)` directly.

**Comment by yosogawa** [comment]
I quickly realized that I could use MidiCommands.send directly.
However, I still don't think it's correct, so I override MidiMessage and use it.

`import 'package:flutter_midi_command/flutter_midi_command_messages.dart';

class MySysExMessage extends MidiMessage {
  List<int> headerData;

  /// System Exclusive Message
  MySysExMessage({this.headerData = const []}) {
    if (kDebugMode) {
      //print("MySysExMessage() [$this.headerData]");
    }
  }

  @override
  void send() {

    List<int> vLengthList = this.headerData.cast<int>().toList();
    vLengthList.insert(0, 0xF0); // Start byte
    vLengthList.add(0xF7); // End byte
    data = Uint8List.fromList(vLengthList);
    super.send();
  }
`

**Comment by mortenboye** [comment]
@yosogawa Feel free to submit a MR with a better interface for SysEx messages.
