### ISSUE TITLE
Example App MidiCommand().devices not finding midi hardware

### ISSUE THREAD

**Issue by TheGifler** [InvisibleWrench/FlutterMidiCommand#106]
I have used the example app to try and see how this program works. 
When I plug in my midi keyboard to my Mac it is all set up and working in Audio Midi Setup.

Tested to make sure that the midi device was working by opening GarageBand and it works fine.

However, when I open the app and try to see the device in the list on iOS emulator there are no results. Additionally the Virtual Midi device is not being recognised or able to be used by other applications. 

When printing out the results from MidiCommand().devices it comes up with no connected devices.

Please be aware I am relatively new to flutter and very new to working with midi.

**Comment by mortenboye** [comment]
I don't think you can expect MIDI devices to come through the simulator from macOS to the emulated iOS. This is not a restriction in FlutterMidiCommand, but in the iOS simulator.

Instead you can maybe try to run the app as a Mac desktop app or on a real device?

**Comment by TheGifler** [comment]
I'll try this and get back to you.
