### ISSUE TITLE
Sending continuous sysex data on iOS need to split packets

### ISSUE THREAD

**Issue by mortenboye** [InvisibleWrench/FlutterMidiCommand#11]

**Comment by zerobits** [comment]
SysEx messages on IOS crashes when data exceeds 3 bytes. At first thought it was unsafe wrapping of optionals but after testing found the continuous sysex messages of variable byte lengths can crash IOS apps. Android doesn't have this issue...

As a quick/temp fix, I've changed line 744 in SwiftFlutterMidiCommandPlugin.swift

sendMidiMsg(message: remainingPacket!.subdata(in: 1..<4))

to 

sendMidiMsg(message: remainingPacket!.subdata(in: 1..<remainingPacket!.count))

**Comment by mortenboye** [comment]
Thank you for this.
I think I will rewrite the entire message parsing section of the iOS plugin in the near future.

**Comment by epaterlini** [comment]
Any news on this? Still using the workaround by @zerobits  ...

**Comment by mortenboye** [comment]
No news in relation to this ticket, which was closed 3 years ago.
Also re-reading the ticket i’m not sure what it even relates to. 
Please create a new ticket describing the issue you see.
