### ISSUE TITLE
Add an option to receive the raw MIDI packets as received from the device without buffering

### ISSUE THREAD

**Issue by intonarumori** [InvisibleWrench/FlutterMidiCommand#111]
I have a use case where I need access to the raw MIDI packets sent by a MIDI device.
Specifically I’d like to circumvent the part of the platform code where the library buffers data to wait for every part of a SysEx transfer to be received first before forwarding it to Flutter.

I'm working with samplers from the `80s where not all parts of the MIDI specifications was formalized, so it's crucial to be able to access incoming data without any buffering.

I've implemented a solution with the following goals in mind:
- Since this is a very specific, advanced use case it should not affect existing code using the library
- I've added a flag to enable "raw MIDI data receiving", which by default is set to `false`
- When enabled it forwards every MIDI packet as received without processing of buffering it first

I've implemented this by modifying the platform interface and added the platfrom specific implementation for iOS here:
https://github.com/InvisibleWrench/FlutterMidiCommand/pull/110
https://github.com/InvisibleWrench/flutter_midi_command_platform_interface/pull/2

Let me know what you think, thanks.

**Comment by mortenboye** [comment]
I can appreciate this use case. 
Just curious, do you intent to handle all midi parsing on your own for all communication or only for SysEx and maybe only sometimes?

The PR contains a bunch of port handling as well. Is that related to your other ticket?

**Comment by intonarumori** [comment]
Thanks for the reply I will open a new PR for this and we can continue with the discussion there. I will close this ticket for now.
