### ISSUE TITLE
NoteOnMessage/NoteOffMessage type reversed

### ISSUE THREAD

**Issue by JePoste** [InvisibleWrench/FlutterMidiCommand#12]
Hello and thank you for your plugin :)

I'm fairly new to MIDI in general so I hope I'm not mistaken, but it seems there is a problem with the NoteOnMessage and NoteOffMessage implementation.

I found a reference array for MIDI commands on this website: https://ccrma.stanford.edu/~craig/articles/linuxmidi/misc/essenmidi.html

> MIDI commands:
>    **0x80     Note Off
>    0x90     Note On**
>    0xA0     Aftertouch
>    0xB0     Continuous controller
>    0xC0     Patch change
>    0xD0     Channel Pressure
>    0xE0     Pitch bend
>    0xF0     (non-musical commands)

But in your implementation, it seems you have reversed the command hexa:

```
class NoteOnMessage extends MidiMessage {
...
  @override
  void send() {
    data = Uint8List(3);
    data[0] = 0x80 + channel;    <========= should be 0x90
    data[1] = note;
    data[2] = velocity;
    super.send();
  }
}

class NoteOffMessage extends MidiMessage {
... 
  @override
  void send() {
    data = Uint8List(3);
    data[0] = 0x90 + channel;    <========= should be 0x80
    data[1] = note;
    data[2] = velocity;
    super.send();
  }
}
```

It seems to be confirmed as when I plug my app into my instrument, it plays a note when calling       `NoteOffMessage(channel: 0, note: 64, velocity: 64).send();`
and stops it when calling
`NoteOnMessage(channel: 0, note: 64, velocity: 64).send();`

**Comment by mortenboye** [comment]
Merged. Thank you.
