### ISSUE TITLE
Incorrect package="com.invisiblewrench.fluttermidicommand" found in source AndroidManifest.xml

### ISSUE THREAD

**Issue by troller2017** [InvisibleWrench/FlutterMidiCommand#122]
I created a flutter project, installed flutter_midi_command, tried to build and this is the error:
```
FAILURE: Build failed with an exception.
Incorrect package="com.invisiblewrench.fluttermidicommand" found in source AndroidManifest.xml
Setting the namespace via the package attribute in the source AndroidManifest.xml is no longer supported.
Recommendation: remove package="com.invisiblewrench.fluttermidicommand" from the source AndroidManifest.xml
```

Flutter 3.24.3
Android SDK version 34
flutter_midi_command: ^0.5.2

**Comment by cliffnmontgomery** [comment]
I experienced the same thing as troller2017. Removing the "package= line from AndroidManifest.xml made it happy (meaning it was then willing to compile and build my app), although I haven't yet tried to run the midi_command example.
