### ISSUE TITLE
Example app does not work on ios with version > 0.1.4

### ISSUE THREAD

**Issue by systemcode** [InvisibleWrench/FlutterMidiCommand#16]
tested on iOS simulator only.
Example app does not work with latest versions 0.1.5 & 0.1.6
On Controls screen no midi output is registered at the device when controls are moved although print debug shows  
flutter: send [176, 102, 10]
PC messages also not working
Version 0.1.4 works OK.

**Comment by mortenboye** [comment]
fixed in 0.1.7

**Comment by systemcode** [comment]
Just to confirm that 0.1.7 tested on iOS simulator and all works fine now. Thanks.
