### ISSUE TITLE
Using with DAW

### ISSUE THREAD

**Issue by ThibaudMZN** [InvisibleWrench/FlutterMidiCommand#18]
Is it possible to send midi to a DAW, and in fact use an iOS or Android app as a midi controller (drum pads for example) ?

**Comment by mortenboye** [comment]
Absolutely.

On Android you can tell your device to act as a USB MIDI device in the "USB Menu"
[link](https://arstechnica.com/gadgets/2015/05/android-m-embraces-usb-type-c-midi-devices/) when connected to your PC/Mac.
On iOS you can connect the device to the MIDI Network Session and send/receive MIDI through that.

Or you can use MIDI over bluetooth which works on both iOS and Android as long as the DAW machine is advertising it's availability on Bluetooth.

Is your DAW running on macOS or Windows?

**Comment by ThibaudMZN** [comment]
Amazing, I didn’t know about this android feature ! I’m using an android phone and Ableton on Windows, so configuration should be pretty straight forward ! I’m scared to use Bluetooth because of the latency, and any way I think ableton doesn’t support it natively ! Thanks for your answer !
