### ISSUE TITLE
android version > 6.0 can't use ble

### ISSUE THREAD

**Issue by ifredom** [InvisibleWrench/FlutterMidiCommand#19]
When Android version is higher than 6.0, Bluetooth function cannot be called normally, and location permission is required

```

  <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"></uses-permission>
  <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"></uses-permission>
```

**Comment by mortenboye** [comment]
Location permissions are listed in the manifest:
[https://github.com/InvisibleWrench/FlutterMidiCommand/blob/master/android/src/main/AndroidManifest.xml](https://github.com/InvisibleWrench/FlutterMidiCommand/blob/master/android/src/main/AndroidManifest.xml)

What is the issue you are seeing? Are permissions not being requested?

**Comment by ifredom** [comment]
In Xiaomi's mobile phone, Android version is higher than 6.0. If Bluetooth is aroused, there will be no reaction. After setting the location permission, it can be called normally

**Comment by mortenboye** [comment]
I'm afraid I don't understand what you mean. I am using this on Android higher that 6.0 without issue. What is different on the Xiaomi phone?

**Comment by mortenboye** [comment]
If there is no further information on this issue. I will close it.

**Comment by ifredom** [comment]
Thank you for your reply. It's settled. The first time the permission is called, there will be no response after that. It may be a problem with the permission to run.
