### ISSUE TITLE
Build fails on android

### ISSUE THREAD

**Issue by TVdata** [InvisibleWrench/FlutterMidiCommand#21]
FAILURE: Build failed with an exception.

     * What went wrong:
     Task 'assembleAarRelease' not found in root project 'flutter_midi_command'.

This is from the example project after flutter build apk.  Running still seems to work, I assume because it's a debug build.

**Comment by TVdata** [comment]
This was jetifier trying to fix the real issue, which was this:
`Execution failed for task ':flutter_midi_command:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
`
I solved the issue by making buildToolsVersion and compileSdkVersion match in build.gradle. Please include this change.
`
    compileSdkVersion 28
    buildToolsVersion "28.0.3"
`

**Comment by mortenboye** [comment]
v0.2.3 is now up, with the suggested changes.
Thank you for your contribution.
