### ISSUE TITLE
Does not build for macos deployment

### ISSUE THREAD

**Issue by systemcode** [InvisibleWrench/FlutterMidiCommand#23]
Trying to build example app to run on macos.
Does not seem to work using 0.2.4 on macos

Flutter (Channel dev, 1.24.0-6.0.pre, on Mac OS X 10.15.7,  XCode 12.1

[!] CocoaPods could not find compatible versions for pod "flutter_midi_command":
In Podfile:
flutter_midi_command (from Flutter/ephemeral/.symlinks/plugins/flutter_midi_command/macos)

Specs satisfying the flutter_midi_command (from Flutter/ephemeral/.symlinks/plugins/flutter_midi_command/macos) dependency were found, but they required a higher minimum deployment target.

**Comment by mortenboye** [comment]
Some data for Xcode was missing in the repo. Can I ask you to try to pull from lastest master and try again?

**Comment by systemcode** [comment]
Sorry no change. Same result as before.
using:

  flutter_midi_command:
    git:
      url: https://github.com/InvisibleWrench/FlutterMidiCommand

**Comment by systemcode** [comment]
Your example now works. Very impressive. Thanks.

However, I cannot immediately see how to retrofit this into my existing project. I can go and merge in the obvious smaller changes but what about my existing project.pbxproj  files?

**Comment by mortenboye** [comment]
Your own project, that depends on this package, will have its own generated Xcode project to run.
The issue here, was that some files were missing for the example project, but your app does not use the example project, only the plugin package.

I have updated the version on pub to 0.2.6, which includes these fixes.

Is this helpful?

**Comment by systemcode** [comment]
I have copied all files in  example/macos   to my project just to try and it does now build and startup (but hangs down the line probably due to other plugins :)

I have been following this BTW>  https://flutter.dev/desktop

OK - I think this is now all at my end so you can close if you want. Thanks again.

**Comment by systemcode** [comment]
Example builds and runs OK.
