### ISSUE TITLE
Network Session 1 missing

### ISSUE THREAD

**Issue by systemcode** [InvisibleWrench/FlutterMidiCommand#24]
When calling MidiCommand.devices,   I have always had "Network Session 1" in the list of devices but now  "Network Session 1" is not found when running on ioS Simulator and Android Simulator as well as real iOS devices. This causes problems now because I cannot debug application which used that interface to connect to MIDI devices connected to the mac.

Actual USB MIDI  devices still appear as wellas Bluetooth devices.

Using v0.2.4

**Comment by mortenboye** [comment]
You are correct. This is a mistake on my part. I will push a fix shortly

**Comment by systemcode** [comment]
Confirming that this now works. Thanks.

**Comment by MikeFP** [comment]
Is there a way to tell if a device is the Network Session one besides its name?

**Comment by mortenboye** [comment]
@MikeFP try the latest dev version. It should work there.

`flutter_midi_command: ^0.4.0-dev.2`

**Comment by MikeFP** [comment]
Works perfectly, thanks!
