### ISSUE TITLE
Example of recording MIDI events and saving to .mid file?

### ISSUE THREAD

**Issue by brylie** [InvisibleWrench/FlutterMidiCommand#25]
I see there is currently work on time stamp support. What would be needed to record a series of MIDI events and write them to a standard MIDI format file? Would you add an example app showing a simple MIDI record/save workflow?

**Comment by mortenboye** [comment]
I have little experience with the .mid file format, but my cursory understanding is that the Midi events in a .mid file are "timestamped" according to a delta-time from the last event based on ticks, i.e. divisions of a quarter note.

As far as an example showing this, that will not be a part of this package, as this is solely a thin layer, bringing MIDI to Flutter. However another package could easily implement such an example and depend on this package for the MIDI communication.

**Comment by ifredom** [comment]
tks for your work. Look forward to giving examples
