### ISSUE TITLE
iOS app fails to launch

### ISSUE THREAD

**Issue by pabolojo** [InvisibleWrench/FlutterMidiCommand#26]
I was playing around with the example given and, in Android, it works fine but in iOS it does not even launch.
I have simplified the sketch several times but the result remains the same. Moreover, I created a new project and just updated the xcode min iOS version to let the package work and included de package in the pubspec.yaml and then the flutter example app does not work anymore.
Any idea on what could be happening?

**Comment by gy** [comment]
Did you update the Podfile to minimum target of `10.0`

Top of the Podfile.
```
platform :ios, '10.0'
```

If that's not it, can you post the error you see?

**Comment by pabolojo** [comment]
Yes, I have updated the Podfile.
There is no error itself, the output that I get is the following:
`Launching lib/main.dart on iPad de Pablo in debug mode...
lib/main.dart:1
Signing iOS app for device deployment using developer identity: "Apple Development: pabloesg26@gmail.com (DNQCV2RL2T)"
Xcode build done.                                           28,3s
Exited`

The app is installed successfully on my iPad and then, when it is launching, it closes it self and in VS Code the "Installing and launching..." message remains without doing nothing.

I am using Flutter 1.22.5 on VS Code 1.52.1 running on a Hackintosh with macOS 11.0.1 (20B29) and the app is being installed on an iPad Air 2 with iOS 14.3

The steps I followed were:

1. Created a new application project
2. Substitute the files in lib by main.dart and controller.dart from this github
3. Add and install the dependencies in the pubspec.yaml
4. Edit the Podfile file under the ios folder, unccommenting and editing the `platform :ios, '10.0'` line
5. Run the app

**Comment by stuartkuentzel** [comment]
I'm having the same issue. The when trying to run it on iPhone, it closes immediately without any error message.

**Comment by mortenboye** [comment]
The issue could be a missing NSBluetoothAlwaysUsageDescription to info.plist in the Xcode project. That will cause an error in the Xcode log and the app will quit immediately.
Flutter Midi Command uses Bluetooth to search for and connect to MIDI BLE devices.

**Comment by stuartkuentzel** [comment]
@mortenboye this was exactly the issue for me. By adding NSBluetoothAlwaysUsageDescription to info.plist, the app launches. Thanks!

**Comment by pabolojo** [comment]
@mortenboye yes, that was my issue too. After adding that everything works fine.
