### ISSUE TITLE
Failed `disconnectDevice`

### ISSUE THREAD

**Issue by noboru-i** [InvisibleWrench/FlutterMidiCommand#29]
I called `MidiCommand.disconnectDevice` after `MidiCommand.connectToDevice`.
But I had the following error. (I use a physical iPod touch device.)

```
[VERBOSE-2:ui_dart_state.cc(186)] Unhandled Exception: PlatformException(MESSAGEERROR, Could not parse device id, {id: D567BA7A-A04C-5A5C-828B-307783CC07CB, name: TD-07 MIDI, type: BLE, connected: false}, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:581:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)
```

I thought,
https://github.com/InvisibleWrench/FlutterMidiCommand/blob/644dd94431eda60724f5ffda4103ac5e096dd263/ios/Classes/SwiftFlutterMidiCommandPlugin.swift#L137 cast to `Dictionary<String, String>`.
But the argument has boolean `connected`.
So you may change like `connectToDevice`.

```
        case "disconnectDevice":
            if let deviceInfo = call.arguments as? Dictionary<String, Any> {
                if let deviceId = deviceInfo["id"] as? String {
                    disconnectDevice(deviceId: deviceId)
                } else {
                    result(FlutterError.init(code: "MESSAGEERROR", message: "No device Id", details: call.arguments))
                }
                result(nil)
            } else {
                result(FlutterError.init(code: "MESSAGEERROR", message: "Could not parse device id", details: call.arguments))
            }
            result(nil)
            break
```

Using:
flutter_midi_command: 0.3.0
flutter: 2.0.4
Xcode: 12.4

**Comment by mortenboye** [comment]
Thank you for reporting this. I will fix it shortly

**Comment by noboru-i** [comment]
Thank you for fixing at https://github.com/InvisibleWrench/FlutterMidiCommand/commit/53c4463a694b77dbd4bef23e2bc76f4d6a0f2189#diff-ae77d1639e5ddd3e023bab3e51dd15bac56600db5a314b6f8e00f0bc36e18cd7R137-R142 👍
