### ISSUE TITLE
Android virtual midi device

### ISSUE THREAD

**Issue by coaqii** [InvisibleWrench/FlutterMidiCommand#34]
Hi!
I was wondering if it is possible to advertise as an android virtual midi device using the library.

This way you could possibly make a companion app to something like MobileSheets.
Right now I am working on an app that connects to a serial bluetooth device and sends serial commands to an arduino.
I was wondering if I could implement a midi device so my app can convert incoming Midi, and send it to an arduino.
When looking at the android SDK documentation is seems possible, but I am just a beginner in app development so I have no idea where to begin.

**Comment by mortenboye** [comment]
I don’t think I fully understand your use case, but creating virtual MIDI device is not in scope for this plugin.
You should however be able to create a new plugin that creates the virtual MIDI device, and use that device with this plugin. If that suites your needs.
