### ISSUE TITLE
In what unit the timestamp is for iOS?

### ISSUE THREAD

**Issue by MikeFP** [InvisibleWrench/FlutterMidiCommand#35]
Reading the iOS native MIDI docs, I found out the packet's timestamp is a value meant to be multiplied by some system factor.

I figured maybe the MidiPacket already did that conversion so the timestamp would be at the same unit regardless of the platform. However, that does not seem to be the case.

So, my question is: does the iOS timestamp need to be multiplied by a factor to be usable? How can I get that factor?

**Comment by MikeFP** [comment]
I'm not sure the docs refer to the same services the package uses, but here you go: https://developer.apple.com/documentation/coremidi/midi_services.

The packet structs ([`MIDIPacket`](https://developer.apple.com/documentation/coremidi/midipacket) and [`MIDIEventPacket`](https://developer.apple.com/documentation/coremidi/midieventpacket/)) both use the [`MIDITimeStamp`](https://developer.apple.com/documentation/coremidi/miditimestamp) struct, which in turn uses [`mach_absolute_time()`](https://developer.apple.com/documentation/kernel/1462446-mach_absolute_time), a clock value in tick units. The docs seem to suggest devs to use `clock_gettime_nsec_np(CLOCK_UPTIME_RAW)` instead, since it returns a value in nanoseconds, but the Core MIDI Framework itself does not use it. After a quick search, I found the correct way to convert from ticks to nanoseconds is by using [`mach_timebase_info()`](https://developer.apple.com/documentation/kernel/mach_timebase_info_data_t), however that requires access to a native function.

**Comment by mortenboye** [comment]
Thank you @MikeFP for the details.

Can I ask you to take a look here https://github.com/InvisibleWrench/FlutterMidiCommand/blob/906e5e15507d84686937b77c4e599b19ebda1cab/ios/Classes/SwiftFlutterMidiCommandPlugin.swift#L786 and let me know if im on the right track here.

**Comment by MikeFP** [comment]
@mortenboye It seems to be working fine. Thanks!

**Comment by mortenboye** [comment]
Great. I'll merge that into the dev branch then.

**Comment by mortenboye** [comment]
this is now merged into 0.4.0-dev.3

Feel free to reopen this, if there are any issues.
