### ISSUE TITLE
Are Virtual MIDI Ports supported?

### ISSUE THREAD

**Issue by gatzsche** [InvisibleWrench/FlutterMidiCommand#38]
Hi, 

thanks for FlutterMidiCommand. It's an awesome plugin.

I currently have the issue of not seeing virtual MIDI ports of other apps running in the background.
Is this feature not supported in general? Or did I implement something wrong?

Thanks for your answer, 
   Gabriel

**Comment by gatzsche** [comment]
They were not. But here they are:
https://github.com/InvisibleWrench/FlutterMidiCommand/pull/39

**Comment by mortenboye** [comment]
Thank you for contributing a PR, I will check it at soon as possible.

**Comment by mortenboye** [comment]
@gatzsche Your PR have now been merged into the dev branch and released on pub as flutter_midi_command 0.4.0-dev.4 and will probably be merged into the main branch soon.
Thanks again for your contribution.
