### ISSUE TITLE
MIDI in events crash the example app

### ISSUE THREAD

**Issue by AlmudenaVila** [InvisibleWrench/FlutterMidiCommand#4]
I've been trying this project, which looks nice by the way, and I haven't found any issues when sending MIDI commands out.

However, it seems that any MIDI in command can crash the example application.

I've tried DEBUG and RELEASE modes just in case and it makes no difference.

The error I get is:
```
I/flutter (31457): setup changed deviceOpened
I/flutter (31457): init controller
E/AndroidRuntime(31457): FATAL EXCEPTION: Thread-3
E/AndroidRuntime(31457): Process: com.invisiblewrench.fluttermidicommandexample, PID: 31457
E/AndroidRuntime(31457): java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: Thread-3
E/AndroidRuntime(31457): 	at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:794)
E/AndroidRuntime(31457): 	at io.flutter.embedding.engine.FlutterJNI.dispatchPlatformMessage(FlutterJNI.java:684)
E/AndroidRuntime(31457): 	at io.flutter.embedding.engine.dart.DartMessenger.send(DartMessenger.java:80)
E/AndroidRuntime(31457): 	at io.flutter.embedding.engine.dart.DartExecutor.send(DartExecutor.java:174)
E/AndroidRuntime(31457): 	at io.flutter.view.FlutterNativeView.send(FlutterNativeView.java:144)
E/AndroidRuntime(31457): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler$EventSinkImplementation.success(EventChannel.java:226)
E/AndroidRuntime(31457): 	at com.invisiblewrench.fluttermidicommand.FlutterMidiCommandPlugin$FlutterStreamHandler.send(FlutterMidiCommandPlugin.kt:261)
E/AndroidRuntime(31457): 	at com.invisiblewrench.fluttermidicommand.FlutterMidiCommandPlugin$RXHandler.onSend(FlutterMidiCommandPlugin.kt:244)
E/AndroidRuntime(31457): 	at android.media.midi.MidiReceiver.send(MidiReceiver.java:128)
E/AndroidRuntime(31457): 	at com.android.internal.midi.MidiDispatcher.onSend(MidiDispatcher.java:91)
E/AndroidRuntime(31457): 	at android.media.midi.MidiReceiver.send(MidiReceiver.java:128)
E/AndroidRuntime(31457): 	at android.media.midi.MidiOutputPort$1.run(MidiOutputPort.java:74)
```

I have found this change in flutter which may be the origin of the problem:
https://github.com/flutter/engine/commit/2c9e37c34e79475bbde7c8163eb5e56cdb9662a1

There is more information here:
https://github.com/flutter/flutter/issues/34993

I think that the example app needs fixing. I am not fluent enough to fix it right now.

Edit: Actually, I think the fix may need to happen in the java/kotlin code not in the flutter app.

Thanks

**Comment by mortenboye** [comment]
Hi, thank you for reporting this issue.
You are indeed correct, this seems to stem from the Kotlin part of the plugin.
Along with a few other changes, I've pushed an update to the plugin, that I believe fixes this.
The update comes with a few breaking API changes, but these should be quite easy to work through.

Thanks again for reporting this.

**Comment by AlmudenaVila** [comment]
I've just tried it and it works. Thanks for the quick reply!
