### ISSUE TITLE
Question: MIDI 2.0 Support?

### ISSUE THREAD

**Issue by kNoAPP** [InvisibleWrench/FlutterMidiCommand#41]
Does this project currently support [the new MIDI 2.0 protocol](https://www.midi.org/midi-articles/details-about-midi-2-0-midi-ci-profiles-and-property-exchange)? I know MIDI 2.0 inherently is backwards compatible and should work with this library, but lets say I want to use 2.0 and get the extra byte of pressure readings. Could I do that with the current library?

**Comment by mortenboye** [comment]
At this point there is no MIDI 2.0 specific features in this library, it mostly wraps the MIDI functions from the OS and adds a little convenience here and there.
But the intention is to implement MIDI 2.0 a set of features and on iOS the CoreMIDI framework has been updated to support this already. 
The Universal Packet Format would be a good place to start I think.

Out of curiosity what devices are you using with MIDI 2.0?

**Comment by kNoAPP** [comment]
Looking to support the wide range of pressure readings from a Steinway Spirio R Piano. Thanks for the swift reply!
