### ISSUE TITLE
Error when Compiling for Android SDK 31 (android:exported needs to be explicitly specified)

### ISSUE THREAD

**Issue by anzbert** [InvisibleWrench/FlutterMidiCommand#47]
I am trying to compile for Android. The app only imports flutter midi command and calls:

MidiCommand().devices.then((value) => print(value));

Compiles fine for IOS, but I am getting an error on the Android version. I cant see flutter midi command in my android manifest files at all, so i dont know where to set 'android:exported' to true.

I hope someone can help me with this one. Ive already tried setting the targetSDK to 30 and it didn't compile either. That time stating that i required at at least sdk 31. I am actually not using any other dependencied, only flutter midi command.

This is the error output:

[/Users/anz/localDev/flutter_sound_board/android/app/src/debug/AndroidManifest.xml:23:9]()-34:19 Error:
	android:exported needs to be explicitly specified for element <service#com.invisiblewrench.fluttermidicommand.VirtualDeviceService>. Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See [https://developer.android.com/guide/topics/manifest/activity-element#exported]() for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugMainManifest'.
> Manifest merger failed : android:exported needs to be explicitly specified for element <service#com.invisiblewrench.fluttermidicommand.VirtualDeviceService>. Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See [https://developer.android.com/guide/topics/manifest/activity-element#exported]() for details.

**Comment by anzbert** [comment]
Ok.. I made it work by adding android:exported="true" to the android/src/main/AndroidManifest.xml in flutter_midi_command library.

I believe there is some update you have to do to accomodate new requirements of Android 12.

Thanks for a great library though. Love your work :)

**Comment by mortenboye** [comment]
Thank you. Your PR have been merged. I will update the published version soon
