### ISSUE TITLE
Cannot figure out how to send Midi Notes via USB

### ISSUE THREAD

**Issue by anzbert** [InvisibleWrench/FlutterMidiCommand#49]
Ok maybe I am a bit silly but I cannot for the life of me figure out how to send a midi note with this library.

i create an instance on MidiCommand with:
MidiCommand midiCommand = MidiCommand();

I have my phone connected via USB and in MIDI mode, and i can also find the MIDI device with:
midiCommand.devices

I pick the correct one (Android USB Peripheral Port) from the resulting array and I can connect to it with:
midiCommand.connectToDevice(selectedDevice)

selectedDevice.connected equals to true to confirm.

Then i am trying to send a note with:
midiCommand.sendData(
                            NoteOnMessage(channel: 1, note: 36, velocity: 127)
                                .data,
                          );

and nothing arrives ?!?!

this is some of the console output:

D[/FlutterMIDICommand]()(24433): list [{name=The Metronome by Soundbrenner, id=1, type=native, connected=false, inputs=[{id=0, connected=false}], outputs=[{id=0, connected=false}]}, {name=Android USB Peripheral Port, id=5, type=native, connected=true, inputs=[{id=0, connected=false}], outputs=[{id=0, connected=false}]}, {name=FlutterMidiCommand, id=12, type=native, connected=false, inputs=[{id=0, connected=false}], outputs=[{id=0, connected=false}]}]

when sending a note i get:
D[/FlutterMIDICommand]()(24433): Send to input port null

hmm why null? i dont understand
am i sending notes wrong? do i have to specify the output port of my phone somehow?

**Comment by anzbert** [comment]
Ok ive tried the example APP and I can receive Midi notes from my Mac over USB perfrectly fine. When changing values in the controller page i also only get this message in the debug console:

D[/FlutterMIDICommand]()(25894): Send to input port null

So receiving works, but sending is unsuccessful?!

**Comment by mortenboye** [comment]
Hi. This indicates that for some reason only one of the ports open. I’m not able to look into it before some time next week, but feel free to poke around. 

Is it the same for all discovered devices or only the USB Peripheral?

**Comment by anzbert** [comment]
thx i was looking at it for a while, but i am not that great at kotlin. might be an opportunity to learn haha. i'll need to check again for other devices.

**Comment by anzbert** [comment]
ok. i reinstalled things and tried again and its now working on my windows PC and macbook. Sorry about the kerfuffle. i'll keep investigating, but i guess for now the issue can be closed.

sorry for being an alarmist
