### ISSUE TITLE
Airplane mode is disabling the App

### ISSUE THREAD

**Issue by odhs** [InvisibleWrench/FlutterMidiCommand#5]
When we switch the phone to airplane mode the application developed with this plugin stops working.
I am not using the Bluetooth part, but even with the Bluetooth permissions on AndroidManifest it happens.

To reproduce the error: Have an app with the app using the plugin, put it in airplane mode, try launching the app.

This has happened since older versions of the plugin.

The app will function normally again if you exit airplane mode and restart Android.

Thanks you!

**Comment by mortenboye** [comment]
Please try the latest, it should resolve this issue

**Comment by odhs** [comment]
In the version 0.1.2 works perfectly!

Thank you a lot!

**Comment by mortenboye** [comment]
Closing
