### ISSUE TITLE
Question : sendData

### ISSUE THREAD

**Issue by akfldk1028** [InvisibleWrench/FlutterMidiCommand#50]
First of all, thank you for making such a nice plugin. I have a question while using sendData() on Android. 
I'm trying to connect a midi file to a synthesizer so that it plays automatically. So I used sendData().  BUT only the first note was played. 
Does this method need to call timestamp multiple times using timer ? Or should I use only the NoteOn event of midifile separately?

**Comment by mortenboye** [comment]
Hi @akfldk1028, this library is not intended to handle midi files as such. Rather it's designed to send and receive midi commands, like for instance PC and CC messages.
However you can send the contents of a midi file to a synth, but it is up to you to read the file and send the various commands, ie. NoteOns and NoteOffs, at the right time.
