### ISSUE TITLE
need help connecting ipad via USB

### ISSUE THREAD

**Issue by anzbert** [InvisibleWrench/FlutterMidiCommand#57]
Hey!
I finally got an ipad to help me with app development. ihave successfully compiled the example app and installed it on my ipad. The problem now is, how do you actually create a USB connection to your pc/mac? I connect the two via usb-c and i get no midi deviced to show?

on android i can connect to the the android midi service , once my usb connection is set to Midi. I am an iOS newb, so please help me!

thx,
Andreas

**Comment by anzbert** [comment]
ok ive got it! 
it only seems to work when connected to a Mac. I had to go into 'Audio Midi Setup' and enable the ipad there for audio and midi connection. 

Does anyone know of a way to make a midi connection with iOS to non-macOS devices via USB ?

**Comment by mortenboye** [comment]
> Does anyone know of a way to make a midi connection with iOS to non-macOS devices via USB ?

iOS doesn’t have a USB mode similar to what you see on android. 

What you can do is get the Apple USB Camera Adapter thingy. 

https://www.apple.com/shop/product/MK0W2AM/A/lightning-to-usb-3-camera-adapter?fnode=de44f4fd2985adcc1d1af36fb0516ac3e8b29dd056746665fa2a291e2c41ef3d5f0c75079aa66d17432965cb1d4a79b552b0289f889f62d9b87c237c8280a067efabb425f6a84458fa710d2e921f8b9e8e255d326cb2d60a5440d2c05dc8e246

It makes your phone/ipad work as a USB Midi host. 
But this is for lightning connectors, not sure how it’s handled on USB-C

What does your setup look like? Is the ipad going to be host or peripheral?

**Comment by anzbert** [comment]
I want to use the iPad as a midi peripheral with USB-c. It does work now
after I enabled it in the audio midi setup. But it does look like Ipados
does not play well as a peripheral midi device with non-apple hardware.

It's a bummer, but typical for apple, I am starting to think 🍎

This Adapter seems to be mostly useful if you want the iPad to be the Midi
host on lightning port iPads, right?

**Comment by anzbert** [comment]
I guess I can close this issue as it is an Apple problem and nothing that can be fixed within this package.
