### ISSUE TITLE
BT message splitting on IOS is wrong

### ISSUE THREAD

**Issue by TheKashe** [InvisibleWrench/FlutterMidiCommand#6]
The code is supposed to split the message by timestamp

    let messages = messageBytes.split { (val) -> Bool in // Split at subseqent timestamps, if any
                    val & 0x80 == 1
    }

But it splits on note off message! As far as I understand BT spec, the 2nd byte of the header is repeated to indicate new midi message, so that should be used to split messages.

**Comment by TheKashe** [comment]
Turns out that Midi over BLE is a bit more complex than splitting by timestamp. The current implementation doesn't work for anything but the simplest examples.

I've tried to implement a better stack, will post pull request.

I assume the same problem is on Android

**Comment by mortenboye** [comment]
I see the problem on iOS.
On Android I see it working, when sending SysEx messages to the MIDI device.
 The android.media.midi API handles BLE devices directly, and mentions: "Support transmission of arbitrary length data for SysEx, etc."
[https://developer.android.com/reference/android/media/midi/package-summary](https://developer.android.com/reference/android/media/midi/package-summary)

But if you found that it does not, then please share an example that fails.

Looking at [BLE-MIDI-spec.pdf](http://www.hangar42.nl/wp-content/uploads/2017/10/BLE-MIDI-spec.pdf) it seems manageable to handle SysEx properly.
