### ISSUE TITLE
iOS version support

### ISSUE THREAD

**Issue by Jon-Salmon** [InvisibleWrench/FlutterMidiCommand#70]
The readme states iOS 10 is supported, but commit 0addb5adda11f8eb19babbeb00789890a253b62f limited support to iOS 11. Which is correct?

**Comment by mortenboye** [comment]
Hi @Jon-Salmon, the readme has not been updated. You should aim for iOS 11.
In fact the whole package is overdue for an update. I'll try to get that done soon.

**Comment by Jon-Salmon** [comment]
Thanks for clarifying and I look forward to it!
