### ISSUE TITLE
Sending Sysex data on Android fails

### ISSUE THREAD

**Issue by intonarumori** [InvisibleWrench/FlutterMidiCommand#75]
I've been developing an application with the library and on an iPad everything works as expected.
I was able to send larger SysEx messages as well with by chunking the data.

However, when I try to use the exact same app on Android I found issues:
- I am able to receive NRPN messages just fine
- However when sending any data NRPN, or smaller SysEx messages, it's not working
- I've closely inspected the incoming and outgoing NRPN messages and they fully match, I feel I eliminated the chance of an error on my side, again with the iOS build it works perfectly.

I was able to use Android studio and track down, that my `sendData` call indeed reaches the desired part of the Kotlin code, however `inputPort` seems to be `null`.

I'm using the 0.4.10 version.

I'm stuck with debugging this issue, and l like to ask for some hints or debugging tips:
- How do you usually develop the library? I was not able to run the example project on an Android device, do you have any tips?
- I found it tricky to debug MIDI sending, since I also have to be connected to a synth via USB, while wireless debugging seems to work, it disconnects sometimes, so I'm not fully trusting it. Any tips on this front?
- I didn't go deeper into custom timestamp yet, maybe timing could be an issue, however even simple one time SysEx messages are failing.

I would really appreciate some tips, I think I could debug this issue with some good hints on how to build the example or efficiently debug only the library and come back with my findings.

Thank you.

Edit: I made some progress:
- I was able to run the example by setting a package name in the `AndroidManifest.xml`
- I set the Android device USB to the MIDI setting, this way I was able to verify that NRPN and other messages are really sent to my computer
- I will look through the example project file to see if my setup is missing some crucial steps and will report back.

**Comment by intonarumori** [comment]
Update: I was able to get it working in my app.
I copied some stuff from the new NRPN code that is not yet in the 0.4.10 version, if you could push a new version that would be great (0.4.11 or similar).

I've also noticed some strange behavior about the device `connected` property being false sometimes, I've yet to narrow it down, but will keep an eye on it and open a new issue if it persists.

We can close this one.

**Comment by maks** [comment]
Great to hear you got it working @intonarumori !
For future reference, you don't necessarily need to copy in the code for packages that have not yet been released on Pub as its possible to [specify git repo's as locations for packages in your pubspec](https://dart.dev/tools/pub/dependencies#git-packages).
