### ISSUE TITLE
Inconsistent sysex messages received on Android

### ISSUE THREAD

**Issue by intonarumori** [InvisibleWrench/FlutterMidiCommand#85]
I'm developing an app that receives 123 bytes in a single syses message.

I've tested my app with the following devices:
- Nothing phone (1) (2022)
- Samsung Galaxy Tab A (2019)
- iPad mini 6 (2020)
- iPhone 13 mini (2021)

Everything works as expected, except on the Nothing Phone (1).
Instead of the 123 bytes, I sometimes receive only 75.

I've opened the generated Android project and started poking around to see if it's an issue with FlutterMidiCommand or the data is already shorter when coming from [`MidiReceiver`](https://developer.android.com/reference/android/media/midi/MidiReceiver) and it looks like it's already corrupted before hitting the plugin.

I've exhausted my ideas on what else to try to make it work and I'm also a bit worried that there might be other Android devices that will have the same issue. Do you have any tips on what else could I try?

Many thanks.

**Comment by mortenboye** [comment]
Hi, for testing you could try the https://github.com/InvisibleWrench/FlutterMidiCommand/tree/selfcontained-ble-midi branch. In that branch BLE is not handled by media.midi, but by the [BLESSED](https://github.com/weliem/blessed-android) library and MIDI parsing is handled directly by the FMC plugin. 
By using BLESSED, better robustness might be achieved on the BLE part, which might help in you situtation.

**Comment by intonarumori** [comment]
I'm a bit confused, I'm not using BLE, but direct USB connection. Do you think the above tip is relevant to that?

**Comment by mortenboye** [comment]
Ah sorry, I did not realize that. Please disregard my previous comment.

Not sure what the underlying issue is.

**Comment by intonarumori** [comment]
Closing this issue for now, as I'm not experiencing this any more. If it pops up again, I will open a new discussion
