### ISSUE TITLE
How to send MIDI Clock?

### ISSUE THREAD

**Issue by guicho0601** [InvisibleWrench/FlutterMidiCommand#86]
I'm trying to send MIDI Clock to my devices. First I realized there isn't a proper function for this type of messages, so, I was trying with the SysExMessage but it fails in the line 101 of the `flutter_midi_command_messages.dart` with this error message:
```[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Unsupported operation: Cannot insert into a fixed-length list```

<img width="532" alt="Captura de pantalla 2023-05-23 a la(s) 11 41 31" src="https://github.com/InvisibleWrench/FlutterMidiCommand/assets/4987144/a3cd2533-2021-499c-b12f-83cef0a01ade">

This is how I'm trying to use the SysExMessage:
<img width="509" alt="Captura de pantalla 2023-05-23 a la(s) 11 44 07" src="https://github.com/InvisibleWrench/FlutterMidiCommand/assets/4987144/06888fa6-de7d-431a-8faf-2fc88309266c">

I will appreciate your help.

**Comment by mortenboye** [comment]
SysEx does not support MIDI Clock, so instead you can send the MIDI clock pulse directly through FMC:

```
var clockPulse = Uint8List.fromList([0xF8]);
MidiCommand().sendData(clockPulse);
```

Do note that MIDI clock defines a tempo by continually sending pulses (usually 24 pulses per quarter note). So 24 times pulses of 0xF8 defines a quarter note tempo.

You can not tell the receiver to run at the speed of X BPMs, by using MIDI standard clock / 0xF8

**Comment by guicho0601** [comment]
Thanks for the help, that is easier than I expected. But, I'm still having some troubles, because I created a Timer.periodic with a duration in microseconds and I'm trying with 120 bpm (208333 microseconds) and my device is jumping between 124 and 130 bpm. Do you know what can I use for send the right time? 

This is my code:
```
int tempo = (60 * 1000 * 1000 * 10 / song.tempo / 24).floor();
    _timer = Timer.periodic(Duration(microseconds: tempo), (timer) {
      MidiCommand().sendData(Uint8List.fromList([0xF8]));
    });
```

I appreciate the help.

**Comment by mortenboye** [comment]
@guicho0601 this might be due to Dart/Flutter being single threaded.
For instance if the Event loop is busy handling micro task, that might occupy the event loop for longer than your timer periods, causing the ticks to trigger at non-exact times.

You can see more here.
https://www.youtube.com/watch?v=vl_AaCgudcY
https://medium.com/@purvajg/microtasks-and-event-loops-in-dart-9f5863f031d8

**Comment by mortenboye** [comment]
@guicho0601 did you manage to work this out? Is it OK to close this issue?
