### ISSUE TITLE
No Network Midi Device visible anymore, when running app in the IOS simulator

### ISSUE THREAD

**Issue by anzbert** [InvisibleWrench/FlutterMidiCommand#88]
Is anyone else having this issue with the latest Xcode and Flutter version?

I used to be able to connect to a Network Midi Session in my own ,as well as in the Example App. The Network Session is activated in Audio Midi Setup on my mac and can be joined by other programs without any issue.

I am just wondering if this is a recent Flutter, Simulator or platform level change that broke this? Anyone else can confirm this issue?

**Comment by mortenboye** [comment]
The trick is to change from the default port of the session from 5004 to something else, 5006 in this case. 
<img width="781" alt="Screenshot 2023-06-19 at 20 16 47" src="https://github.com/InvisibleWrench/FlutterMidiCommand/assets/604314/5007217c-33f3-424b-aa88-e0008ca57e85">

https://stackoverflow.com/a/43686052

**Comment by anzbert** [comment]
Thx Morten!

Unfortunately, this is not working for me. It always used to work without any changes needed as well. Anyone else have this issue? 

I hope I can get to the bottom of this.

**Comment by anzbert** [comment]
It works again. i never figured out what the problem was, but some macOS, Xcode or Flutter update must have fixed it. 
Closing this issue now.
