### ISSUE TITLE
IllegalArgumentException after closing an app by "back" button

### ISSUE THREAD

**Issue by brun0xon** [InvisibleWrench/FlutterMidiCommand#9]
> E/AndroidRuntime(16189): java.lang.RuntimeException: Unable to destroy activity {com.editor.bulakhov/com.getbrain.bulakhov.MainActivity}: java.lang.IllegalArgumentException: Receiver not registered: com.invisiblewrench.fluttermidicommand.FlutterMidiCommandPlugin$broadcastReceiver$1@65e4335
> E/AndroidRuntime(16189): 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4496)
> E/AndroidRuntime(16189): 	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4515)
> E/AndroidRuntime(16189): 	at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:39)
> E/AndroidRuntime(16189): 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
> E/AndroidRuntime(16189): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
> E/AndroidRuntime(16189): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
> E/AndroidRuntime(16189): 	at android.os.Handler.dispatchMessage(Handler.java:106)
> E/AndroidRuntime(16189): 	at android.os.Looper.loop(Looper.java:193)
> E/AndroidRuntime(16189): 	at android.app.ActivityThread.main(ActivityThread.java:6718)
> E/AndroidRuntime(16189): 	at java.lang.reflect.Method.invoke(Native Method)
> E/AndroidRuntime(16189): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
> E/AndroidRuntime(16189): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
> E/AndroidRuntime(16189): Caused by: java.lang.IllegalArgumentException: Receiver not registered: com.invisiblewrench.fluttermidicommand.FlutterMidiCommandPlugin$broadcastReceiver$1@65e4335
> E/AndroidRuntime(16189): 	at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1271)
> E/AndroidRuntime(16189): 	at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1504)
> E/AndroidRuntime(16189): 	at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:659)
> E/AndroidRuntime(16189): 	at com.invisiblewrench.fluttermidicommand.FlutterMidiCommandPlugin.teardown(FlutterMidiCommandPlugin.kt:279)
> E/AndroidRuntime(16189): 	at com.invisiblewrench.fluttermidicommand.FlutterMidiCommandPlugin$Companion$registerWith$1.onViewDestroy(FlutterMidiCommandPlugin.kt:43)
> E/AndroidRuntime(16189): 	at io.flutter.app.FlutterPluginRegistry.onViewDestroy(FlutterPluginRegistry.java:232)
> E/AndroidRuntime(16189): 	at io.flutter.app.FlutterActivityDelegate.onDestroy(FlutterActivityDelegate.java:235)
> E/AndroidRuntime(16189): 	at io.flutter.app.FlutterActivity.onDestroy(FlutterActivity.java:106)
> E/AndroidRuntime(16189): 	at android.app.Activity.performDestroy(Activity.java:7403)
> E/AndroidRuntime(16189): 	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1306)
> E/AndroidRuntime(16189): 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4481)
> E/AndroidRuntime(16189): 	... 11 more

Looks like the problem is in unregistering unregistered receiver for the bluetooth

**Comment by mortenboye** [comment]
I see the problem, will look into this.

**Comment by mortenboye** [comment]
A new version is up, please let me know if the issue persists

**Comment by brun0xon** [comment]
it's alright
