### ISSUE TITLE
Example doesn't work on Linux

### ISSUE THREAD

**Issue by acfsmith** [InvisibleWrench/FlutterMidiCommand#92]
I'm trying to run example on Linux:

`git clone https://github.com/InvisibleWrench/FlutterMidiCommand.git`
`cd FlutterMidiCommand/example/`
`flutter build linux --release`
`./build/linux/x64/release/bundle/example`

It shows following error messages:

`flutter: MissingPluginException(No implementation found for method listen on channel plugins.invisiblewrench.com/flutter_midi_command/setup_channel)`
`flutter: #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:308)`
`flutter: <asynchronous suspension>`
`flutter: #1      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:652)`
`flutter: <asynchronous suspension>`

**Comment by mortenboye** [comment]
@maks do you know?

**Comment by maks** [comment]
hmm I just updated to latest on the master branch here and I do see the same error trying to run the example on Linux.
I haven't done anything with the plugin in Flutter for a little while so I'm not sure when it broke, but it definitely used to work.
I don't have time right now, but I can look into this when I do and see whats broken @mortenboye if you or someone else doesn't get to it first.

**Comment by mortenboye** [comment]
Fixed in 0.4.13
