### ISSUE TITLE
Midi sysex receive error 

### ISSUE THREAD

**Issue by johnparboandersen** [InvisibleWrench/FlutterMidiCommand#93]
When sending a short sysex message to the example project, I get the following error: The 'plugins.invisiblewrench.com/flutter_midi_command/rx_channel' channel sent a message from native to Flutter on a non-platform thread. Platform channel messages must be sent on the platform thread. Failure to do so may result in data loss or crashes, and must be fixed in the plugin or application code creating that channel.
See https://docs.flutter.dev/platform-integration/platform-channels#channels-and-platform-threading for more information.

I see the same error in my own app, but only after updating to the latest Flutter version. I am on Mac.

**Comment by mortenboye** [comment]
Thanks for reporting this. Indeed the latest flutter version seems to be more picky about this.

I've made a PR here, https://github.com/InvisibleWrench/FlutterMidiCommand/pull/94
If you have a change please check that out and let me know if that does not solve the issue.

**Comment by johnparboandersen** [comment]
Hi Morten. The issues seems to be fixed with the PR #94, thanks a lot
